[package]
name = "nu_plugin_pnet"
license = "MIT"
authors = ["Carson <c@rson.riker.me>", "Darren.Schroeder"]
keywords = ["nushell", "network", "plugin"]
homepage = "https://github.com/fennewald/nu_plugin_pnet"
repository = "https://github.com/fennewald/nu_plugin_pnet"
description = "A nushell plugin for enumerating network interfaces in a platform-agnostic way"
version = "1.2.0"
edition = "2021"
readme = "README.md"

[dependencies]
pnet = { version = "0.31", features = ["std"] }
nu-plugin = { path = "../nushell/crates/nu-plugin", version = "0.73.1" }
nu-protocol = { path = "../nushell/crates/nu-protocol", version = "0.73.1", features = [
    "plugin",
] }
